CUDA_VISIBLE_DEVICES=0 python train.py --name  usps_to_mnist_v23 \
   	--resize_or_crop='resize_and_crop' \
    --loadSize=28 --fineSize=28 --which_model_netD 'basic' \
    --which_model_netG 'resnet_6blocks' \
    --model cycle_gan_socher --input_nc 1 --output_nc 1\
    --lambda_A 10 --lambda_B 10 --lambda_identity 2 \
    --display_id 1 --which_model_netM 'LeNet'\
    --no_flip --batchSize 128 \
    --dataset_mode usps_mnist --dataroot_A /scratch/users/aditya/data/ \
    --dataroot_B /scratch/users/aditya/data/ \
    --dataroot /scratch/users/aditya/data/ \
    --which_direction AtoB --no_html --nThreads 8 --Mmodel_path /home/users/aditya/sohan/cycada/runs/LeNet/usps/v102/checkpoints/iter70.pth \
    --num_cls 10 --niter 200 --niter_decay 100 --lr 2e-4 --save_epoch_freq 20 --lr_policy 'plateau'